const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("zeno", {
  getConfig: () => ipcRenderer.invoke("config:get"),
  setConfig: (partial) => ipcRenderer.invoke("config:set", partial),
  chat: (payload) => ipcRenderer.invoke("ai:chat", payload),
  chatStream: (payload) => ipcRenderer.invoke("ai:chat-stream", payload),
  onAiDelta: (callback) => ipcRenderer.on("ai:delta", (_event, payload) => callback(payload)),
  checkUpdate: () => ipcRenderer.invoke("app:update-check"),
  appVersion: () => ipcRenderer.invoke("app:version"),
  listen: () => ipcRenderer.invoke("os:listen"),
  cancelListen: () => ipcRenderer.invoke("os:listen-cancel"),
  genImage: (prompt) => ipcRenderer.invoke("ai:image", prompt),
  runAction: (action) => ipcRenderer.invoke("os:action", action),
  getStats: () => ipcRenderer.invoke("os:stats"),
  screenLook: () => ipcRenderer.invoke("os:screen-look"),
  clipboardRead: () => ipcRenderer.invoke("os:clipboard-read"),
  clipboardWrite: (text) => ipcRenderer.invoke("os:clipboard-write", text),
  memList: () => ipcRenderer.invoke("mem:list"),
  memAdd: (fact) => ipcRenderer.invoke("mem:add", fact),
  memClear: () => ipcRenderer.invoke("mem:clear"),
  todoList: () => ipcRenderer.invoke("todo:list"),
  todoAdd: (text) => ipcRenderer.invoke("todo:add", text),
  todoDone: (match) => ipcRenderer.invoke("todo:done", match),
  todoClear: () => ipcRenderer.invoke("todo:clear"),
  onWake: (callback) => ipcRenderer.on("zeno:wake", callback),
  getWeather: (city) => ipcRenderer.invoke("net:weather", city),
  chatsList: () => ipcRenderer.invoke("chats:list"),
  chatsSave: (session) => ipcRenderer.invoke("chats:save", session),
  chatsLoad: (id) => ipcRenderer.invoke("chats:load", id),
  chatsDelete: (id) => ipcRenderer.invoke("chats:delete", id),
  pluginsList: () => ipcRenderer.invoke("plugins:list"),
  pluginsRun: (name, input) => ipcRenderer.invoke("plugins:run", { name, input }),
  listModels: () => ipcRenderer.invoke("ai:models"),
  getCredits: () => ipcRenderer.invoke("ai:credits"),
  openExternal: (url) => ipcRenderer.invoke("open:external", url)
});
